export const styleBox = {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 400,
    bgcolor: 'background.paper',
    border: '1px solid #000',
    pt: 2,
    px: 4,
    pb: 3,
};
export const styleModal = {
    mt: 2,
    bgcolor: '#f5f5f5',
    borderRadius: 2,
    p: 2,
    boxShadow: 2,
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '500px',
    maxHeight: '80vh',
    overflowY: 'auto',
}
